--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
DROP TABLE "JGM"."BOARD_TBL" cascade constraints;
DROP TABLE "JGM"."USER_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table BOARD_TBL
--------------------------------------------------------

  CREATE TABLE "JGM"."BOARD_TBL" 
   (	"BOARD_NO" NUMBER, 
	"BOARD_SUBJECT" VARCHAR2(50 BYTE), 
	"BOARD_CONTENT" VARCHAR2(500 BYTE), 
	"BOARD_WRITER" VARCHAR2(50 BYTE), 
	"BOARD_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"BOARD_VIEWCOUNT" NUMBER DEFAULT 0, 
	"BOARD_LIKECOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_TBL
--------------------------------------------------------

  CREATE TABLE "JGM"."USER_TBL" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PW" VARCHAR2(40 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"USER_AGE" NUMBER, 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_PHONE" VARCHAR2(20 BYTE), 
	"USER_ADDRESS" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JGM.BOARD_TBL
SET DEFINE OFF;
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (1,'게시글1','내용1','admin',to_timestamp('23/08/08 15:36:24.732000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (2,'게시글2','내용2','admin',to_timestamp('23/08/08 15:36:35.356000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (3,'게시글3','내용3','admin',to_timestamp('23/08/08 15:36:39.743000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (4,'게시글4','내용4','admin',to_timestamp('23/08/08 15:36:44.309000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (5,'게시글5','내용5','admin',to_timestamp('23/08/08 15:36:48.042000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (6,'게시글6','내용6','admin',to_timestamp('23/08/08 15:36:51.965000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (7,'게시글7','내용7','admin',to_timestamp('23/08/08 15:36:57.701000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (8,'게시글8','내용8','admin',to_timestamp('23/08/08 15:37:02.109000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (9,'게시글9','내용9','admin',to_timestamp('23/08/08 15:37:06.713000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (10,'게시글10','내용10','admin10',to_timestamp('23/08/08 15:37:15.423000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
Insert into JGM.BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_VIEWCOUNT,BOARD_LIKECOUNT) values (11,'게시글12','내용12','admin12',to_timestamp('23/08/08 15:39:24.096000000','RR/MM/DD HH24:MI:SSXFF'),0,0);
REM INSERTING into JGM.USER_TBL
SET DEFINE OFF;
Insert into JGM.USER_TBL (USER_ID,USER_PW,USER_NAME,USER_AGE,USER_EMAIL,USER_PHONE,USER_ADDRESS) values ('khuser01','pass01','일용자',32,'khuser01@kh.com','0104214531','서울시 중구');
Insert into JGM.USER_TBL (USER_ID,USER_PW,USER_NAME,USER_AGE,USER_EMAIL,USER_PHONE,USER_ADDRESS) values ('1111','1111','1111',11111,'111@111','111','111');
--------------------------------------------------------
--  DDL for Index SYS_C007341
--------------------------------------------------------

  CREATE UNIQUE INDEX "JGM"."SYS_C007341" ON "JGM"."BOARD_TBL" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007331
--------------------------------------------------------

  CREATE UNIQUE INDEX "JGM"."SYS_C007331" ON "JGM"."USER_TBL" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD_TBL
--------------------------------------------------------

  ALTER TABLE "JGM"."BOARD_TBL" ADD PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_TBL
--------------------------------------------------------

  ALTER TABLE "JGM"."USER_TBL" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JGM"."USER_TBL" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "JGM"."USER_TBL" MODIFY ("USER_PW" NOT NULL ENABLE);
